name: CI

on:
  push:
    branches: [ main, '**/issue*', '**/issues*', '**/feature*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm check
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
